services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: createrington_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: createrington_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - createrington-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: createrington-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@createrington.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - createrington-network

volumes:
  postgres_data:

networks:
  createrington-network:
    driver: bridge
